# Generated by Django 4.0.4 on 2023-01-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_historicalreview_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquestion',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Содержание'),
        ),
    ]
