# Generated by Django 4.0.4 on 2023-01-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_historicalquestion_title_alter_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcategory',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalreview',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaltemplate',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
